# Generated by Django 3.2.19 on 2023-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('food_type', models.CharField(choices=[("Chill 'n Thrill", "Chill 'n Thrill"), ('Savoury Temptations', 'Savoury Temptations'), ('Sweet Tooth Hugs', 'Sweet Tooth Hugs'), ('Liquid Delights', 'Liquid Delights')], max_length=25, verbose_name='food_type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(related_name='item', to='restaurant.Category'),
        ),
    ]
