# Generated by Django 3.2.19 on 2023-07-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230704_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name'], 'verbose_name': 'menu item', 'verbose_name_plural': 'menuitems'},
        ),
    ]
